# force-rebuild: 2026-02-25T21:10:00Z
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
